name: End to End tests

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run mac:prod
