name: End to End tests

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      - name: Checkout
        uses: actions/checkout@v2.7.0
      
      - name: Print EMAIL and PW
        run: echo "${{ secrets.TEST_EMAIL }}"
        
      - name: Cypress.io
        uses: cypress-io/github-action@v5.6.1
        with:
          browser: chrome
          build: npx cypress run ENVIRONMENT=prod email='$EMAIL' password='$PW' --browser chrome
          start: npm start
        env: 
          EMAIL: ${{ secrets.TEST_EMAIL }}
          PW: ${{secrets.TEST_PW}}
     
       
 
        
