name: End to End tests

on: [push]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0

      - name: Cypress.io
        uses: cypress-io/github-action@v5.6.1
        with:
          browser: chrome
          build: npm run win:ci:prod
          start: npm start
        env:
          EMAIL: ${{ secrets.TEST_EMAIL }}
          PW: ${{ secrets.TEST_PW }}
          
      - name: Retrieve Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
